server:
  port:9086
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show-sql: true
          use_sql_comments: false
          format_sql: false
  logging:
    pattern:
      console: "%d(yyyy-MM-dd HH:mm:ss) ${LOG_LEVEL_PATTERN:~%5P} %m%n"




spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.show-sql = true
spring.h2.console.enabled = true
spring.jpa.hibernate.ddl-auto = create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
logging.level.org.springframework.security=DEBUG
jwt_secret='julio1979secret',
jwt-expiration-milliseconds=604800000
